# Generated by Django 4.2.29 on 2026-03-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='contact_address',
            field=models.CharField(default='Rr. Kiro Kistoski DRNC nr. 39, Tetovo', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='contact_phone',
            field=models.CharField(default='+389 70 000 00', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='opening_hours',
            field=models.CharField(default='Mon-Fri: 10:00 - 22:00 | Sat: 10:00 - 16:00', max_length=255),
        ),
    ]
