# Generated by Django 4.2.29 on 2026-03-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitecontent_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='blog_meta_description',
            field=models.TextField(blank=True, help_text='SEO description for the blog page'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='blog_subtitle',
            field=models.TextField(blank=True, default='Stay motivated with tips, stories, and insights from the Ar-Re community.', help_text='Subtitle or short description under the blog title'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='blog_title',
            field=models.CharField(default='Our Blog', help_text='Main title shown on the Blog page', max_length=255),
        ),
    ]
