# Generated by Django 4.2.29 on 2026-03-31 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitecontent_blog_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='blog_meta_description',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='blog_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='blog_title',
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary for blog listing page')),
                ('content', models.TextField(help_text='Full blog post content (you can use HTML)')),
                ('image', models.ImageField(blank=True, help_text='Featured image for the post', null=True, upload_to='blog/images/')),
                ('is_published', models.BooleanField(default=False, help_text='Check to make this post visible on the website')),
                ('published_at', models.DateTimeField(blank=True, help_text='When this post was published', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
