# Generated by Django 4.2.29 on 2026-04-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blogcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
