# Generated by Django 4.2.29 on 2026-04-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_blogpost_options_alter_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='contact_email',
            field=models.EmailField(default='ar.re.fitness@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='contact_phone',
            field=models.CharField(default='+389 71 742 874', max_length=50),
        ),
    ]
